apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ollama
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: ollama
    model: {{ .Values.model.name }}
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
