apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
  generation: 1
  labels:
    app: cartservice1
  name: cartservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        alicloud.service.tag: v1
        app: cartservice1
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: {{ .Values.application.name.prefix}}cartservice
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}cartservice
    spec:
      containers:
      - env:
        - name: spring.cloud.nacos.discovery.server-addr
          value: {{ .Values.mse.address.springcloud}}
        - name: dubbo.registry.address
          value: {{ .Values.mse.address.dubbo}}
        - name: JAVA_TOOL_OPTIONS
          value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
        - name: dubbo.consumer.check
          value: "false"
        image: {{ .Values.image.prefix }}cartservice:{{ .Values.image.version }}
        imagePullPolicy: Always
        name: cartservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
