apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cart-redis
  selfLink: /api/v1/namespaces/default/services/cart-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: cart-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
