apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
  generation: 1
  labels:
    app: cart-redis
  name: cart-redis
  selfLink: /apis/apps/v1/namespaces/default/deployments/cart-redis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: cart-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cart-redis
    spec:
      containers:
        - image: images.onwalk.net/public/microservice-demo/redis:latest 
          imagePullPolicy: Always
          name: cart-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
