apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkoutservice
  name: checkoutservice
  selfLink: /apis/apps/v1/namespaces/default/deployments/checkoutservice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        alicloud.service.tag: v2
        app: checkoutservice
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}checkoutservice
    spec:
      containers:
        - env:
            - name: spring.cloud.nacos.discovery.server-addr
              value: {{ .Values.mse.address.springcloud}}
            - name: dubbo.registry.address
              value: {{ .Values.mse.address.dubbo}}
            - name: JAVA_TOOL_OPTIONS
              value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
            - name: dubbo.consumer.check
              value: "false"
          image: {{ .Values.image.prefix }}checkoutservice:{{ .Values.image.version }}
          imagePullPolicy: Always
          name: checkoutservice
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
