apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
  creationTimestamp: null
  generation: 1
  labels:
    app: frontend3
  name: frontend3
  selfLink: /apis/apps/v1/namespaces/default/deployments/frontend3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: frontend3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        alicloud.service.tag: tag3
        app: frontend3
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: {{ .Values.application.name.prefix}}frontend
        msePilotAutoEnable: "on"
        msePilotCreateAppName: {{ .Values.application.name.prefix}}frontend
    spec:
      containers:
      - env:
        - name: demo_version
          value: "true"
        - name: spring.cloud.nacos.discovery.server-addr
          value: {{ .Values.mse.address.springcloud}}
        - name: dubbo.registry.address
          value: {{ .Values.mse.address.dubbo}}
        - name: JAVA_TOOL_OPTIONS
          value: ' -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 '
        - name: dubbo.consumer.check
          value: "false"
        image: {{ .Values.image.prefix }}frontend:{{ .Values.image.version }}
        imagePullPolicy: Always
        name: frontend-v2
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
