apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: product-mysql
  selfLink: /api/v1/namespaces/default/services/product-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: product-mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
