# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: onwalk.net
  namespace: monitoring
  secretName: observable-server-tls
prometheus:
  enabled: true
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    remote_write:
      - name: remote_prometheus
        url: https://data-gateway.svc.plus/api/v1/write
    ingress:
      ingressClassName: nginx
      hosts:
        - prometheus.onwalk.net
      tls:
        - secretName: observable-server-tls
          hosts:
            - prometheus.onwalk.net
    alertmanagers:
    - static_configs:
      - targets:
        - alertmanager.onwalk.net
  serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/config/alerting_rules.yml
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
deepflow:
  enabled: true
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.onwalk.net
      tls:
        - secretName: observable-server-tls
          hosts:
            - grafana.onwalk.net
influxdb:
  enabled: true
  ingress:
    enabled: true
    tls: true
    secretName: observable-server-tls
    hostname: influxdb.onwalk.net
    className: nginx
alertmanger:
  enabled: true
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: alertmanager.onwalk.net
    tls:
       - secretName: observable-server-tls
         hosts:
           - alertmanager.onwalk.net
neo4j:
  enabled: false
grafana:
  enabled: false
